# Site settings
title: "Site Title"
email: "email address"
description: "Description"
url: http://segroupproject.github.io

# Build settings
markdown: kramdown
highlighter: pygments

permalink: /:year/:month/:day/:title

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      category: post
